define moodle::instance (
  String $install_dir,
  String $install_provider,
  String $download_url,
  String $moodle_version,
  String $default_lang,
  String $wwwrooturl,
  String $www_owner,
  String $www_group,
  String $dataroot,
  Boolean $create_db,
  Boolean $create_db_user,
  String $dbtype,
  String $dbhost,
  String $dbname,
  String $dbuser,
  String $dbpass,
  Integer $dbport,
  Integer $dbsocket,
  String $prefix,
  String $fullname,
  String $shortname,
  String $summary,
  String $adminuser,
  String $adminpass,
  String $adminemail,
  Hash $plugins = {},
) {
  moodle::db { "${dbhost}/${dbname}":
    create_db      => $create_db,
    create_db_user => $create_db_user,
    dbname         => $dbname,
    dbhost         => $dbhost,
    dbuser         => $dbuser,
    dbpass         => $dbpass,
  }

  moodle::app { $install_dir:
    install_dir      => $install_dir,
    install_provider => $install_provider,
    download_url     => $download_url,
    moodle_version   => $moodle_version,
    default_lang     => $default_lang,
    wwwrooturl       => $wwwrooturl,
    www_owner        => $www_owner,
    www_group        => $www_group,
    dataroot         => $dataroot,
    dbtype           => $dbtype,
    dbhost           => $dbhost,
    dbname           => $dbname,
    dbuser           => $dbuser,
    dbpass           => $dbpass,
    dbport           => $dbport,
    dbsocket         => $dbsocket,
    prefix           => $prefix,
    fullname         => $fullname,
    shortname        => $shortname,
    summary          => $summary,
    adminuser        => $adminuser,
    adminpass        => $adminpass,
    adminemail       => $adminemail,
    plugins          => $plugins,
    require          => Moodle::Db["${dbhost}/${dbname}"],
  }
}
